### ISSUE TITLE
data

### ISSUE THREAD

**Issue by Sickle-and-Hammer** [SaifNOUMA/Network-Traffic-Prediction#1]
Hello, I am very interested in your work, can you give me this data /home/senouma/stage2020/saif/version6/，If possible, please send the data set to the mailbox: 1600144184@qq.com, thank you very much!

**Comment by SaifNOUMA** [comment]
The data set used in this project is located under the folder data.

**Comment by Sickle-and-Hammer** [comment]
> The data set used in this project is located under the folder data.

Thank you for your response and your contribution. I'm a novice, so I don't know where the dataset is, but I knew some time ago and thank you for replying to me in your busy schedule.
